### ISSUE TITLE
No schema information after test

### ISSUE THREAD

**Issue by xtbirihan** [ROBROICH/Display-and-search-SAP-Flight-Model-data-in-a-Microsoft-Power-App#3]
Hi Roman, 

My tests are successfully executed, but when I try to get the output of the FLIGHT_LIST, Call Sap Function stays inactive and I am not able to expand it. However, PowerApps can expandable and I see that flow is successful. 

Best Regards.

**Comment by ROBROICH** [comment]
Hi Hasan,

some thoughts: 
1) Could you please attach some screenshots? 
2) Are you able to call/test the BAPI with you SAP user in SAP GUI?
https://blogs.sap.com/2020/09/06/how-to-test-bapi-function-module-in-sap/
3) Did you do an authorization trace? 
4) Did you install the .NET Connector for SAP in the data gateway VM?
https://support.sap.com/en/product/connectors/msnet.html

Best regards,
Roman

**Comment by xtbirihan** [comment]
I installed all products that you mentioned. test call was successful. I also set external break-point to SAP system and power app flow triggered the break-point. As you can see in the photo, first step(Power apps) can expandable, so i can see input and output fields for the first step, but the second step(Call SAP Function) looks inactive, i clicked several times but i can't able to expand and see input-output fields.


<img width="742" alt="Flow" src="https://user-images.githubusercontent.com/37446714/119682741-cc0a8c00-be4b-11eb-92d9-d3691149c1a4.PNG">
